window.esdocSearchIndex = [
  [
    "dether.shop/src/components/inputs/combobox/styles.js~dropdownbtn",
    "variable/index.html#static-variable-DropDownBtn",
    "<span>DropDownBtn</span> <span class=\"search-result-import-path\">dether.shop/src/components/Inputs/ComboBox/styles.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/helpers/geocodeapi/geocodeapi.js~geocodeapi",
    "variable/index.html#static-variable-GeocodeAPI",
    "<span>GeocodeAPI</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/geocodeAPI/geocodeAPI.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/components/headings/headings.js~h1",
    "variable/index.html#static-variable-H1",
    "<span>H1</span> <span class=\"search-result-import-path\">dether.shop/src/components/Headings/Headings.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/components/headings/headings.js~h2",
    "variable/index.html#static-variable-H2",
    "<span>H2</span> <span class=\"search-result-import-path\">dether.shop/src/components/Headings/Headings.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/components/headings/headings.js~h3",
    "variable/index.html#static-variable-H3",
    "<span>H3</span> <span class=\"search-result-import-path\">dether.shop/src/components/Headings/Headings.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/components/inputs/autoaddress/inputstatusicon.js~inputstatusicon",
    "variable/index.html#static-variable-InputStatusIcon",
    "<span>InputStatusIcon</span> <span class=\"search-result-import-path\">dether.shop/src/components/Inputs/AutoAddress/InputStatusIcon.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/components/inputs/combobox/styles.js~inputstatusicon",
    "variable/index.html#static-variable-InputStatusIcon",
    "<span>InputStatusIcon</span> <span class=\"search-result-import-path\">dether.shop/src/components/Inputs/ComboBox/styles.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/components/inputs/input/inputstatusicon.js~inputstatusicon",
    "variable/index.html#static-variable-InputStatusIcon",
    "<span>InputStatusIcon</span> <span class=\"search-result-import-path\">dether.shop/src/components/Inputs/Input/InputStatusIcon.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/components/inputs/input/inputwrapper.js~inputwrapper",
    "variable/index.html#static-variable-InputWrapper",
    "<span>InputWrapper</span> <span class=\"search-result-import-path\">dether.shop/src/components/Inputs/Input/InputWrapper.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/components/layout/layout.js~layout",
    "variable/index.html#static-variable-Layout",
    "<span>Layout</span> <span class=\"search-result-import-path\">dether.shop/src/components/Layout/Layout.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/components/loader/loader.js~loader",
    "variable/index.html#static-variable-Loader",
    "<span>Loader</span> <span class=\"search-result-import-path\">dether.shop/src/components/Loader/Loader.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/components/spaces/spaces.js~margin",
    "variable/index.html#static-variable-Margin",
    "<span>Margin</span> <span class=\"search-result-import-path\">dether.shop/src/components/Spaces/Spaces.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/components/mention/mention.js~mention",
    "variable/index.html#static-variable-Mention",
    "<span>Mention</span> <span class=\"search-result-import-path\">dether.shop/src/components/Mention/Mention.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/components/inputs/combobox/styles.js~noresultitem",
    "variable/index.html#static-variable-NoResultItem",
    "<span>NoResultItem</span> <span class=\"search-result-import-path\">dether.shop/src/components/Inputs/ComboBox/styles.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/components/spaces/spaces.js~padding",
    "variable/index.html#static-variable-Padding",
    "<span>Padding</span> <span class=\"search-result-import-path\">dether.shop/src/components/Spaces/Spaces.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/components/panels/panels.js~panels",
    "variable/index.html#static-variable-Panels",
    "<span>Panels</span> <span class=\"search-result-import-path\">dether.shop/src/components/Panels/Panels.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/components/inputs/combobox/styles.js~resultitem",
    "variable/index.html#static-variable-ResultItem",
    "<span>ResultItem</span> <span class=\"search-result-import-path\">dether.shop/src/components/Inputs/ComboBox/styles.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/components/inputs/combobox/styles.js~results",
    "variable/index.html#static-variable-Results",
    "<span>Results</span> <span class=\"search-result-import-path\">dether.shop/src/components/Inputs/ComboBox/styles.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/components/inputs/combobox/styles.js~searchfield",
    "variable/index.html#static-variable-SearchField",
    "<span>SearchField</span> <span class=\"search-result-import-path\">dether.shop/src/components/Inputs/ComboBox/styles.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/components/inputs/combobox/styles.js~wrapper",
    "variable/index.html#static-variable-Wrapper",
    "<span>Wrapper</span> <span class=\"search-result-import-path\">dether.shop/src/components/Inputs/ComboBox/styles.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/actions/app/app.js~acceptterms",
    "function/index.html#static-function-acceptTerms",
    "<span>acceptTerms</span> <span class=\"search-result-import-path\">dether.shop/src/actions/app/app.js</span>",
    "function"
  ],
  [
    "dether.shop/src/actions/shop/shop.js~addshop",
    "function/index.html#static-function-addShop",
    "<span>addShop</span> <span class=\"search-result-import-path\">dether.shop/src/actions/shop/shop.js</span>",
    "function"
  ],
  [
    "dether.shop/src/actions/transaction/transaction.js~addtransaction",
    "function/index.html#static-function-addTransaction",
    "<span>addTransaction</span> <span class=\"search-result-import-path\">dether.shop/src/actions/transaction/transaction.js</span>",
    "function"
  ],
  [
    "dether.shop/src/actions/user/user.js~checkusercertified",
    "function/index.html#static-function-checkUserCertified",
    "<span>checkUserCertified</span> <span class=\"search-result-import-path\">dether.shop/src/actions/user/user.js</span>",
    "function"
  ],
  [
    "dether.shop/src/actions/app/app.js~closenotificationmodal",
    "function/index.html#static-function-closeNotificationModal",
    "<span>closeNotificationModal</span> <span class=\"search-result-import-path\">dether.shop/src/actions/app/app.js</span>",
    "function"
  ],
  [
    "dether.shop/src/helpers/calendar/calendar.js~convertcalendar",
    "function/index.html#static-function-convertCalendar",
    "<span>convertCalendar</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/calendar/calendar.js</span>",
    "function"
  ],
  [
    "dether.shop/src/helpers/calendar/calendar.js~convertday",
    "function/index.html#static-function-convertDay",
    "<span>convertDay</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/calendar/calendar.js</span>",
    "function"
  ],
  [
    "dether.shop/src/helpers/ethereum/deleteshop.js~deleteshop",
    "function/index.html#static-function-deleteShop",
    "<span>deleteShop</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/ethereum/deleteShop.js</span>",
    "function"
  ],
  [
    "dether.shop/src/translate/en/en.js~en",
    "variable/index.html#static-variable-en",
    "<span>en</span> <span class=\"search-result-import-path\">dether.shop/src/translate/en/en.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/containers/addshop/form/fromstate.js~fromstate",
    "function/index.html#static-function-fromState",
    "<span>fromState</span> <span class=\"search-result-import-path\">dether.shop/src/containers/AddShop/Form/fromState.js</span>",
    "function"
  ],
  [
    "dether.shop/src/helpers/get/get.js~get",
    "function/index.html#static-function-get",
    "<span>get</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/get/get.js</span>",
    "function"
  ],
  [
    "dether.shop/src/helpers/ethereum/utils.js~getaddress",
    "function/index.html#static-function-getAddress",
    "<span>getAddress</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/ethereum/utils.js</span>",
    "function"
  ],
  [
    "dether.shop/src/helpers/ethereum/getbalance.js~getbalance",
    "function/index.html#static-function-getBalance",
    "<span>getBalance</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/ethereum/getBalance.js</span>",
    "function"
  ],
  [
    "dether.shop/src/helpers/ethereum/utils.js~getdethercontract",
    "function/index.html#static-function-getDetherContract",
    "<span>getDetherContract</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/ethereum/utils.js</span>",
    "function"
  ],
  [
    "dether.shop/src/helpers/ethereum/utils.js~getdthcontract",
    "function/index.html#static-function-getDthContract",
    "<span>getDthContract</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/ethereum/utils.js</span>",
    "function"
  ],
  [
    "dether.shop/src/helpers/apiresponse/apiresponse.js~geterrormessage",
    "function/index.html#static-function-getErrorMessage",
    "<span>getErrorMessage</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/apiResponse/apiResponse.js</span>",
    "function"
  ],
  [
    "dether.shop/src/helpers/ethereum/getlicenceshop.js~getlicenceshop",
    "function/index.html#static-function-getLicenceShop",
    "<span>getLicenceShop</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/ethereum/getLicenceShop.js</span>",
    "function"
  ],
  [
    "dether.shop/src/helpers/ethereum/utils.js~getnetworkid",
    "function/index.html#static-function-getNetworkId",
    "<span>getNetworkId</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/ethereum/utils.js</span>",
    "function"
  ],
  [
    "dether.shop/src/helpers/ethereum/getshop.js~getshop",
    "function/index.html#static-function-getShop",
    "<span>getShop</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/ethereum/getShop.js</span>",
    "function"
  ],
  [
    "dether.shop/src/helpers/ethereum/utils.js~getsmscontract",
    "function/index.html#static-function-getSmsContract",
    "<span>getSmsContract</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/ethereum/utils.js</span>",
    "function"
  ],
  [
    "dether.shop/src/helpers/ethereum/gettransactionstatus.js~gettransactionstatus",
    "function/index.html#static-function-getTransactionStatus",
    "<span>getTransactionStatus</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/ethereum/getTransactionStatus.js</span>",
    "function"
  ],
  [
    "dether.shop/src/styles/globalstyles.js~globalstyles",
    "variable/index.html#static-variable-globalStyles",
    "<span>globalStyles</span> <span class=\"search-result-import-path\">dether.shop/src/styles/globalStyles.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/constants/browser.js~hassupportedbrowser",
    "variable/index.html#static-variable-hasSupportedBrowser",
    "<span>hasSupportedBrowser</span> <span class=\"search-result-import-path\">dether.shop/src/constants/browser.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/helpers/calendar/calendar.js~hours",
    "variable/index.html#static-variable-hours",
    "<span>hours</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/calendar/calendar.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/actions/app/app.js~initializeclientinfo",
    "function/index.html#static-function-initializeClientInfo",
    "<span>initializeClientInfo</span> <span class=\"search-result-import-path\">dether.shop/src/actions/app/app.js</span>",
    "function"
  ],
  [
    "dether.shop/src/helpers/ethereum/issmsreg.js~issmsreg",
    "function/index.html#static-function-isSmsReg",
    "<span>isSmsReg</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/ethereum/isSmsReg.js</span>",
    "function"
  ],
  [
    "dether.shop/src/helpers/ethereum/isweb3.js~isweb3",
    "function/index.html#static-function-isWeb3",
    "<span>isWeb3</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/ethereum/isWeb3.js</span>",
    "function"
  ],
  [
    "dether.shop/src/helpers/ethereum/iszoneshopopen.js~iszoneshopopen",
    "function/index.html#static-function-isZoneShopOpen",
    "<span>isZoneShopOpen</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/ethereum/isZoneShopOpen.js</span>",
    "function"
  ],
  [
    "dether.shop/src/helpers/last/last.js~last",
    "function/index.html#static-function-last",
    "<span>last</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/last/last.js</span>",
    "function"
  ],
  [
    "dether.shop/src/styles/medias.js~mobile",
    "function/index.html#static-function-mobile",
    "<span>mobile</span> <span class=\"search-result-import-path\">dether.shop/src/styles/medias.js</span>",
    "function"
  ],
  [
    "dether.shop/src/constants/notifications.js~notifications",
    "variable/index.html#static-variable-notifications",
    "<span>notifications</span> <span class=\"search-result-import-path\">dether.shop/src/constants/notifications.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/constants/notifications.js~notificationstypes",
    "variable/index.html#static-variable-notificationsTypes",
    "<span>notificationsTypes</span> <span class=\"search-result-import-path\">dether.shop/src/constants/notifications.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/actions/app/app.js~opennotificationmodal",
    "function/index.html#static-function-openNotificationModal",
    "<span>openNotificationModal</span> <span class=\"search-result-import-path\">dether.shop/src/actions/app/app.js</span>",
    "function"
  ],
  [
    "dether.shop/src/helpers/parse/parse.js~parseerror",
    "function/index.html#static-function-parseError",
    "<span>parseError</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/parse/parse.js</span>",
    "function"
  ],
  [
    "dether.shop/src/helpers/timers/timers.js~phoneverificationtime",
    "function/index.html#static-function-phoneVerificationTime",
    "<span>phoneVerificationTime</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/timers/timers.js</span>",
    "function"
  ],
  [
    "dether.shop/src/constants/prefixephone.js~prefixephone",
    "variable/index.html#static-variable-prefixePhone",
    "<span>prefixePhone</span> <span class=\"search-result-import-path\">dether.shop/src/constants/prefixePhone.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/actions/shop/shop.js~removeshop",
    "function/index.html#static-function-removeShop",
    "<span>removeShop</span> <span class=\"search-result-import-path\">dether.shop/src/actions/shop/shop.js</span>",
    "function"
  ],
  [
    "dether.shop/src/actions/root/root.js~reset",
    "function/index.html#static-function-reset",
    "<span>reset</span> <span class=\"search-result-import-path\">dether.shop/src/actions/root/root.js</span>",
    "function"
  ],
  [
    "dether.shop/src/actions/transaction/transaction.js~resettransaction",
    "function/index.html#static-function-resetTransaction",
    "<span>resetTransaction</span> <span class=\"search-result-import-path\">dether.shop/src/actions/transaction/transaction.js</span>",
    "function"
  ],
  [
    "dether.shop/src/reducers/index.js~rootreducer",
    "function/index.html#static-function-rootReducer",
    "<span>rootReducer</span> <span class=\"search-result-import-path\">dether.shop/src/reducers/index.js</span>",
    "function"
  ],
  [
    "dether.shop/src/helpers/scrolltop/scrolltop.js~scrolltotop",
    "function/index.html#static-function-scrollToTop",
    "<span>scrollToTop</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/scrollTop/scrollTop.js</span>",
    "function"
  ],
  [
    "dether.shop/src/actions/kyc/kyc.js~sendsms",
    "function/index.html#static-function-sendSms",
    "<span>sendSms</span> <span class=\"search-result-import-path\">dether.shop/src/actions/kyc/kyc.js</span>",
    "function"
  ],
  [
    "dether.shop/src/actions/kyc/kyc.js~sendverifcode",
    "function/index.html#static-function-sendVerifCode",
    "<span>sendVerifCode</span> <span class=\"search-result-import-path\">dether.shop/src/actions/kyc/kyc.js</span>",
    "function"
  ],
  [
    "dether.shop/src/actions/app/app.js~setappinitialized",
    "function/index.html#static-function-setAppInitialized",
    "<span>setAppInitialized</span> <span class=\"search-result-import-path\">dether.shop/src/actions/app/app.js</span>",
    "function"
  ],
  [
    "dether.shop/src/actions/user/user.js~setbalance",
    "function/index.html#static-function-setBalance",
    "<span>setBalance</span> <span class=\"search-result-import-path\">dether.shop/src/actions/user/user.js</span>",
    "function"
  ],
  [
    "dether.shop/src/actions/shop/shop.js~setdatashoppending",
    "function/index.html#static-function-setDataShopPending",
    "<span>setDataShopPending</span> <span class=\"search-result-import-path\">dether.shop/src/actions/shop/shop.js</span>",
    "function"
  ],
  [
    "dether.shop/src/actions/user/user.js~setethaddress",
    "function/index.html#static-function-setEthAddress",
    "<span>setEthAddress</span> <span class=\"search-result-import-path\">dether.shop/src/actions/user/user.js</span>",
    "function"
  ],
  [
    "dether.shop/src/actions/app/app.js~setethnetwork",
    "function/index.html#static-function-setEthNetwork",
    "<span>setEthNetwork</span> <span class=\"search-result-import-path\">dether.shop/src/actions/app/app.js</span>",
    "function"
  ],
  [
    "dether.shop/src/actions/app/app.js~setlicenceprice",
    "function/index.html#static-function-setLicencePrice",
    "<span>setLicencePrice</span> <span class=\"search-result-import-path\">dether.shop/src/actions/app/app.js</span>",
    "function"
  ],
  [
    "dether.shop/src/actions/app/app.js~setmetamaskinstalled",
    "function/index.html#static-function-setMetamaskInstalled",
    "<span>setMetamaskInstalled</span> <span class=\"search-result-import-path\">dether.shop/src/actions/app/app.js</span>",
    "function"
  ],
  [
    "dether.shop/src/actions/kyc/kyc.js~setphone",
    "function/index.html#static-function-setPhone",
    "<span>setPhone</span> <span class=\"search-result-import-path\">dether.shop/src/actions/kyc/kyc.js</span>",
    "function"
  ],
  [
    "dether.shop/src/actions/kyc/kyc.js~setphonecountry",
    "function/index.html#static-function-setPhoneCountry",
    "<span>setPhoneCountry</span> <span class=\"search-result-import-path\">dether.shop/src/actions/kyc/kyc.js</span>",
    "function"
  ],
  [
    "dether.shop/src/actions/kyc/kyc.js~setphonesent",
    "function/index.html#static-function-setPhoneSent",
    "<span>setPhoneSent</span> <span class=\"search-result-import-path\">dether.shop/src/actions/kyc/kyc.js</span>",
    "function"
  ],
  [
    "dether.shop/src/actions/user/user.js~setphoneverified",
    "function/index.html#static-function-setPhoneVerified",
    "<span>setPhoneVerified</span> <span class=\"search-result-import-path\">dether.shop/src/actions/user/user.js</span>",
    "function"
  ],
  [
    "dether.shop/src/helpers/shake/shake.js~setshake",
    "function/index.html#static-function-setShake",
    "<span>setShake</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/shake/shake.js</span>",
    "function"
  ],
  [
    "dether.shop/src/actions/transaction/transaction.js~settransactionhash",
    "function/index.html#static-function-setTransactionHash",
    "<span>setTransactionHash</span> <span class=\"search-result-import-path\">dether.shop/src/actions/transaction/transaction.js</span>",
    "function"
  ],
  [
    "dether.shop/src/helpers/timers/timers.js~timesince",
    "function/index.html#static-function-timeSince",
    "<span>timeSince</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/timers/timers.js</span>",
    "function"
  ],
  [
    "dether.shop/src/helpers/calendar/calendar.js~times",
    "variable/index.html#static-variable-times",
    "<span>times</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/calendar/calendar.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/helpers/calendar/calendar.js~timesobj",
    "variable/index.html#static-variable-timesObj",
    "<span>timesObj</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/calendar/calendar.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/helpers/ethereum/utils.js~tonbytes",
    "function/index.html#static-function-toNBytes",
    "<span>toNBytes</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/ethereum/utils.js</span>",
    "function"
  ],
  [
    "dether.shop/src/actions/app/app.js~toggletermsmodal",
    "function/index.html#static-function-toggleTermsModal",
    "<span>toggleTermsModal</span> <span class=\"search-result-import-path\">dether.shop/src/actions/app/app.js</span>",
    "function"
  ],
  [
    "dether.shop/src/styles/tokens.js~tokens",
    "variable/index.html#static-variable-tokens",
    "<span>tokens</span> <span class=\"search-result-import-path\">dether.shop/src/styles/tokens.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/helpers/array/array.js~uniquearray",
    "function/index.html#static-function-uniqueArray",
    "<span>uniqueArray</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/array/array.js</span>",
    "function"
  ],
  [
    "dether.shop/src/helpers/wait/wait.js~wait",
    "function/index.html#static-function-wait",
    "<span>wait</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/wait/wait.js</span>",
    "function"
  ],
  [
    "dether.shop/src/helpers/ethereum/utils.js~web3js",
    "variable/index.html#static-variable-web3js",
    "<span>web3js</span> <span class=\"search-result-import-path\">dether.shop/src/helpers/ethereum/utils.js</span>",
    "variable"
  ],
  [
    "dether.shop/src/constants/time.js~weekdays",
    "variable/index.html#static-variable-weekDays",
    "<span>weekDays</span> <span class=\"search-result-import-path\">dether.shop/src/constants/time.js</span>",
    "variable"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/actions/app/app.js",
    "file/src/actions/app/app.js.html",
    "src/actions/app/app.js",
    "file"
  ],
  [
    "src/actions/app/index.js",
    "file/src/actions/app/index.js.html",
    "src/actions/app/index.js",
    "file"
  ],
  [
    "src/actions/index.js",
    "file/src/actions/index.js.html",
    "src/actions/index.js",
    "file"
  ],
  [
    "src/actions/kyc/index.js",
    "file/src/actions/kyc/index.js.html",
    "src/actions/kyc/index.js",
    "file"
  ],
  [
    "src/actions/kyc/kyc.js",
    "file/src/actions/kyc/kyc.js.html",
    "src/actions/kyc/kyc.js",
    "file"
  ],
  [
    "src/actions/map/index.js",
    "file/src/actions/map/index.js.html",
    "src/actions/map/index.js",
    "file"
  ],
  [
    "src/actions/root/index.js",
    "file/src/actions/root/index.js.html",
    "src/actions/root/index.js",
    "file"
  ],
  [
    "src/actions/root/root.js",
    "file/src/actions/root/root.js.html",
    "src/actions/root/root.js",
    "file"
  ],
  [
    "src/actions/shop/index.js",
    "file/src/actions/shop/index.js.html",
    "src/actions/shop/index.js",
    "file"
  ],
  [
    "src/actions/shop/shop.js",
    "file/src/actions/shop/shop.js.html",
    "src/actions/shop/shop.js",
    "file"
  ],
  [
    "src/actions/transaction/index.js",
    "file/src/actions/transaction/index.js.html",
    "src/actions/transaction/index.js",
    "file"
  ],
  [
    "src/actions/transaction/transaction.js",
    "file/src/actions/transaction/transaction.js.html",
    "src/actions/transaction/transaction.js",
    "file"
  ],
  [
    "src/actions/user/index.js",
    "file/src/actions/user/index.js.html",
    "src/actions/user/index.js",
    "file"
  ],
  [
    "src/actions/user/user.js",
    "file/src/actions/user/user.js.html",
    "src/actions/user/user.js",
    "file"
  ],
  [
    "src/bootstrap/app/index.js",
    "file/src/bootstrap/App/index.js.html",
    "src/bootstrap/App/index.js",
    "file"
  ],
  [
    "src/bootstrap/router/index.js",
    "file/src/bootstrap/Router/index.js.html",
    "src/bootstrap/Router/index.js",
    "file"
  ],
  [
    "src/bootstrap/index.js",
    "file/src/bootstrap/index.js.html",
    "src/bootstrap/index.js",
    "file"
  ],
  [
    "src/components/animations/shake/index.js",
    "file/src/components/Animations/Shake/index.js.html",
    "src/components/Animations/Shake/index.js",
    "file"
  ],
  [
    "src/components/animations/index.js",
    "file/src/components/Animations/index.js.html",
    "src/components/Animations/index.js",
    "file"
  ],
  [
    "src/components/button/index.js",
    "file/src/components/Button/index.js.html",
    "src/components/Button/index.js",
    "file"
  ],
  [
    "src/components/buttonlink/index.js",
    "file/src/components/ButtonLink/index.js.html",
    "src/components/ButtonLink/index.js",
    "file"
  ],
  [
    "src/components/flows/transactionflow/index.js",
    "file/src/components/Flows/TransactionFlow/index.js.html",
    "src/components/Flows/TransactionFlow/index.js",
    "file"
  ],
  [
    "src/components/header/index.js",
    "file/src/components/Header/index.js.html",
    "src/components/Header/index.js",
    "file"
  ],
  [
    "src/components/headings/headings.js",
    "file/src/components/Headings/Headings.js.html",
    "src/components/Headings/Headings.js",
    "file"
  ],
  [
    "src/components/headings/index.js",
    "file/src/components/Headings/index.js.html",
    "src/components/Headings/index.js",
    "file"
  ],
  [
    "src/components/icon/index.js",
    "file/src/components/Icon/index.js.html",
    "src/components/Icon/index.js",
    "file"
  ],
  [
    "src/components/inputs/autoaddress/inputstatusicon.js",
    "file/src/components/Inputs/AutoAddress/InputStatusIcon.js.html",
    "src/components/Inputs/AutoAddress/InputStatusIcon.js",
    "file"
  ],
  [
    "src/components/inputs/autoaddress/index.js",
    "file/src/components/Inputs/AutoAddress/index.js.html",
    "src/components/Inputs/AutoAddress/index.js",
    "file"
  ],
  [
    "src/components/inputs/combobox/index.js",
    "file/src/components/Inputs/ComboBox/index.js.html",
    "src/components/Inputs/ComboBox/index.js",
    "file"
  ],
  [
    "src/components/inputs/combobox/styles.js",
    "file/src/components/Inputs/ComboBox/styles.js.html",
    "src/components/Inputs/ComboBox/styles.js",
    "file"
  ],
  [
    "src/components/inputs/input/inputstatusicon.js",
    "file/src/components/Inputs/Input/InputStatusIcon.js.html",
    "src/components/Inputs/Input/InputStatusIcon.js",
    "file"
  ],
  [
    "src/components/inputs/input/inputwrapper.js",
    "file/src/components/Inputs/Input/InputWrapper.js.html",
    "src/components/Inputs/Input/InputWrapper.js",
    "file"
  ],
  [
    "src/components/inputs/input/index.js",
    "file/src/components/Inputs/Input/index.js.html",
    "src/components/Inputs/Input/index.js",
    "file"
  ],
  [
    "src/components/inputs/labeledinput/index.js",
    "file/src/components/Inputs/LabeledInput/index.js.html",
    "src/components/Inputs/LabeledInput/index.js",
    "file"
  ],
  [
    "src/components/inputs/select/index.js",
    "file/src/components/Inputs/Select/index.js.html",
    "src/components/Inputs/Select/index.js",
    "file"
  ],
  [
    "src/components/inputs/switchinput/index.js",
    "file/src/components/Inputs/SwitchInput/index.js.html",
    "src/components/Inputs/SwitchInput/index.js",
    "file"
  ],
  [
    "src/components/inputs/textarea/index.js",
    "file/src/components/Inputs/TextArea/index.js.html",
    "src/components/Inputs/TextArea/index.js",
    "file"
  ],
  [
    "src/components/inputs/index.js",
    "file/src/components/Inputs/index.js.html",
    "src/components/Inputs/index.js",
    "file"
  ],
  [
    "src/components/layout/layout.js",
    "file/src/components/Layout/Layout.js.html",
    "src/components/Layout/Layout.js",
    "file"
  ],
  [
    "src/components/layout/index.js",
    "file/src/components/Layout/index.js.html",
    "src/components/Layout/index.js",
    "file"
  ],
  [
    "src/components/loader/loader.js",
    "file/src/components/Loader/Loader.js.html",
    "src/components/Loader/Loader.js",
    "file"
  ],
  [
    "src/components/loader/index.js",
    "file/src/components/Loader/index.js.html",
    "src/components/Loader/index.js",
    "file"
  ],
  [
    "src/components/mapicons/index.js",
    "file/src/components/MapIcons/index.js.html",
    "src/components/MapIcons/index.js",
    "file"
  ],
  [
    "src/components/marker/index.js",
    "file/src/components/Marker/index.js.html",
    "src/components/Marker/index.js",
    "file"
  ],
  [
    "src/components/mention/mention.js",
    "file/src/components/Mention/Mention.js.html",
    "src/components/Mention/Mention.js",
    "file"
  ],
  [
    "src/components/mention/index.js",
    "file/src/components/Mention/index.js.html",
    "src/components/Mention/index.js",
    "file"
  ],
  [
    "src/components/message/index.js",
    "file/src/components/Message/index.js.html",
    "src/components/Message/index.js",
    "file"
  ],
  [
    "src/components/modal/index.js",
    "file/src/components/Modal/index.js.html",
    "src/components/Modal/index.js",
    "file"
  ],
  [
    "src/components/panels/panels.js",
    "file/src/components/Panels/Panels.js.html",
    "src/components/Panels/Panels.js",
    "file"
  ],
  [
    "src/components/panels/index.js",
    "file/src/components/Panels/index.js.html",
    "src/components/Panels/index.js",
    "file"
  ],
  [
    "src/components/progressbar/index.js",
    "file/src/components/ProgressBar/index.js.html",
    "src/components/ProgressBar/index.js",
    "file"
  ],
  [
    "src/components/roundiconbtn/index.js",
    "file/src/components/RoundIconBtn/index.js.html",
    "src/components/RoundIconBtn/index.js",
    "file"
  ],
  [
    "src/components/screens/loaderscreen/index.js",
    "file/src/components/Screens/LoaderScreen/index.js.html",
    "src/components/Screens/LoaderScreen/index.js",
    "file"
  ],
  [
    "src/components/screens/index.js",
    "file/src/components/Screens/index.js.html",
    "src/components/Screens/index.js",
    "file"
  ],
  [
    "src/components/searchbarwrapper/index.js",
    "file/src/components/SearchBarWrapper/index.js.html",
    "src/components/SearchBarWrapper/index.js",
    "file"
  ],
  [
    "src/components/shoprecap/index.js",
    "file/src/components/ShopRecap/index.js.html",
    "src/components/ShopRecap/index.js",
    "file"
  ],
  [
    "src/components/smalllink/index.js",
    "file/src/components/SmallLink/index.js.html",
    "src/components/SmallLink/index.js",
    "file"
  ],
  [
    "src/components/spaces/spaces.js",
    "file/src/components/Spaces/Spaces.js.html",
    "src/components/Spaces/Spaces.js",
    "file"
  ],
  [
    "src/components/spaces/index.js",
    "file/src/components/Spaces/index.js.html",
    "src/components/Spaces/index.js",
    "file"
  ],
  [
    "src/components/svg/svgarrowup/index.js",
    "file/src/components/Svg/SvgArrowUp/index.js.html",
    "src/components/Svg/SvgArrowUp/index.js",
    "file"
  ],
  [
    "src/components/svg/svgavatar/index.js",
    "file/src/components/Svg/SvgAvatar/index.js.html",
    "src/components/Svg/SvgAvatar/index.js",
    "file"
  ],
  [
    "src/components/svg/svgdether/index.js",
    "file/src/components/Svg/SvgDether/index.js.html",
    "src/components/Svg/SvgDether/index.js",
    "file"
  ],
  [
    "src/components/svg/svghome/index.js",
    "file/src/components/Svg/SvgHome/index.js.html",
    "src/components/Svg/SvgHome/index.js",
    "file"
  ],
  [
    "src/components/svg/svgrefresh/index.js",
    "file/src/components/Svg/SvgRefresh/index.js.html",
    "src/components/Svg/SvgRefresh/index.js",
    "file"
  ],
  [
    "src/components/svg/index.js",
    "file/src/components/Svg/index.js.html",
    "src/components/Svg/index.js",
    "file"
  ],
  [
    "src/components/svg/template.js",
    "file/src/components/Svg/template.js.html",
    "src/components/Svg/template.js",
    "file"
  ],
  [
    "src/components/index.js",
    "file/src/components/index.js.html",
    "src/components/index.js",
    "file"
  ],
  [
    "src/constants/api.js",
    "file/src/constants/api.js.html",
    "src/constants/api.js",
    "file"
  ],
  [
    "src/constants/browser.js",
    "file/src/constants/browser.js.html",
    "src/constants/browser.js",
    "file"
  ],
  [
    "src/constants/config.js",
    "file/src/constants/config.js.html",
    "src/constants/config.js",
    "file"
  ],
  [
    "src/constants/exchanges.js",
    "file/src/constants/exchanges.js.html",
    "src/constants/exchanges.js",
    "file"
  ],
  [
    "src/constants/index.js",
    "file/src/constants/index.js.html",
    "src/constants/index.js",
    "file"
  ],
  [
    "src/constants/notifications.js",
    "file/src/constants/notifications.js.html",
    "src/constants/notifications.js",
    "file"
  ],
  [
    "src/constants/prefixephone.js",
    "file/src/constants/prefixePhone.js.html",
    "src/constants/prefixePhone.js",
    "file"
  ],
  [
    "src/constants/time.js",
    "file/src/constants/time.js.html",
    "src/constants/time.js",
    "file"
  ],
  [
    "src/containers/addshop/form/daysonpeninghour/index.js",
    "file/src/containers/AddShop/Form/DaysOnpeningHour/index.js.html",
    "src/containers/AddShop/Form/DaysOnpeningHour/index.js",
    "file"
  ],
  [
    "src/containers/addshop/form/searchbar/index.js",
    "file/src/containers/AddShop/Form/SearchBar/index.js.html",
    "src/containers/AddShop/Form/SearchBar/index.js",
    "file"
  ],
  [
    "src/containers/addshop/form/fromstate.js",
    "file/src/containers/AddShop/Form/fromState.js.html",
    "src/containers/AddShop/Form/fromState.js",
    "file"
  ],
  [
    "src/containers/addshop/form/index.js",
    "file/src/containers/AddShop/Form/index.js.html",
    "src/containers/AddShop/Form/index.js",
    "file"
  ],
  [
    "src/containers/addshop/form/validator.js",
    "file/src/containers/AddShop/Form/validator.js.html",
    "src/containers/AddShop/Form/validator.js",
    "file"
  ],
  [
    "src/containers/addshop/verification/index.js",
    "file/src/containers/AddShop/Verification/index.js.html",
    "src/containers/AddShop/Verification/index.js",
    "file"
  ],
  [
    "src/containers/addshop/index.js",
    "file/src/containers/AddShop/index.js.html",
    "src/containers/AddShop/index.js",
    "file"
  ],
  [
    "src/containers/home/termsvalidation/index.js",
    "file/src/containers/Home/TermsValidation/index.js.html",
    "src/containers/Home/TermsValidation/index.js",
    "file"
  ],
  [
    "src/containers/home/index.js",
    "file/src/containers/Home/index.js.html",
    "src/containers/Home/index.js",
    "file"
  ],
  [
    "src/containers/leftpanel/index.js",
    "file/src/containers/LeftPanel/index.js.html",
    "src/containers/LeftPanel/index.js",
    "file"
  ],
  [
    "src/containers/map/googlemapwrapper/index.js",
    "file/src/containers/Map/GoogleMapWrapper/index.js.html",
    "src/containers/Map/GoogleMapWrapper/index.js",
    "file"
  ],
  [
    "src/containers/map/infocard/shopcard/index.js",
    "file/src/containers/Map/InfoCard/ShopCard/index.js.html",
    "src/containers/Map/InfoCard/ShopCard/index.js",
    "file"
  ],
  [
    "src/containers/map/infocard/index.js",
    "file/src/containers/Map/InfoCard/index.js.html",
    "src/containers/Map/InfoCard/index.js",
    "file"
  ],
  [
    "src/containers/map/markers/shopmarker/index.js",
    "file/src/containers/Map/Markers/ShopMarker/index.js.html",
    "src/containers/Map/Markers/ShopMarker/index.js",
    "file"
  ],
  [
    "src/containers/map/searchbar/index.js",
    "file/src/containers/Map/SearchBar/index.js.html",
    "src/containers/Map/SearchBar/index.js",
    "file"
  ],
  [
    "src/containers/map/index.js",
    "file/src/containers/Map/index.js.html",
    "src/containers/Map/index.js",
    "file"
  ],
  [
    "src/containers/phoneverification/certifypending/index.js",
    "file/src/containers/PhoneVerification/CertifyPending/index.js.html",
    "src/containers/PhoneVerification/CertifyPending/index.js",
    "file"
  ],
  [
    "src/containers/phoneverification/phoneform/index.js",
    "file/src/containers/PhoneVerification/PhoneForm/index.js.html",
    "src/containers/PhoneVerification/PhoneForm/index.js",
    "file"
  ],
  [
    "src/containers/phoneverification/validatecode/index.js",
    "file/src/containers/PhoneVerification/ValidateCode/index.js.html",
    "src/containers/PhoneVerification/ValidateCode/index.js",
    "file"
  ],
  [
    "src/containers/phoneverification/index.js",
    "file/src/containers/PhoneVerification/index.js.html",
    "src/containers/PhoneVerification/index.js",
    "file"
  ],
  [
    "src/containers/shoprouter/index.js",
    "file/src/containers/ShopRouter/index.js.html",
    "src/containers/ShopRouter/index.js",
    "file"
  ],
  [
    "src/containers/showshop/index.js",
    "file/src/containers/ShowShop/index.js.html",
    "src/containers/ShowShop/index.js",
    "file"
  ],
  [
    "src/containers/wrapper/notificationmodal/index.js",
    "file/src/containers/Wrapper/NotificationModal/index.js.html",
    "src/containers/Wrapper/NotificationModal/index.js",
    "file"
  ],
  [
    "src/containers/wrapper/index.js",
    "file/src/containers/Wrapper/index.js.html",
    "src/containers/Wrapper/index.js",
    "file"
  ],
  [
    "src/containers/index.js",
    "file/src/containers/index.js.html",
    "src/containers/index.js",
    "file"
  ],
  [
    "src/helpers/apiresponse/apiresponse.js",
    "file/src/helpers/apiResponse/apiResponse.js.html",
    "src/helpers/apiResponse/apiResponse.js",
    "file"
  ],
  [
    "src/helpers/apiresponse/index.js",
    "file/src/helpers/apiResponse/index.js.html",
    "src/helpers/apiResponse/index.js",
    "file"
  ],
  [
    "src/helpers/array/array.js",
    "file/src/helpers/array/array.js.html",
    "src/helpers/array/array.js",
    "file"
  ],
  [
    "src/helpers/array/index.js",
    "file/src/helpers/array/index.js.html",
    "src/helpers/array/index.js",
    "file"
  ],
  [
    "src/helpers/calendar/calendar.js",
    "file/src/helpers/calendar/calendar.js.html",
    "src/helpers/calendar/calendar.js",
    "file"
  ],
  [
    "src/helpers/calendar/index.js",
    "file/src/helpers/calendar/index.js.html",
    "src/helpers/calendar/index.js",
    "file"
  ],
  [
    "src/helpers/ethereum/deleteshop.js",
    "file/src/helpers/ethereum/deleteShop.js.html",
    "src/helpers/ethereum/deleteShop.js",
    "file"
  ],
  [
    "src/helpers/ethereum/getbalance.js",
    "file/src/helpers/ethereum/getBalance.js.html",
    "src/helpers/ethereum/getBalance.js",
    "file"
  ],
  [
    "src/helpers/ethereum/getlicenceshop.js",
    "file/src/helpers/ethereum/getLicenceShop.js.html",
    "src/helpers/ethereum/getLicenceShop.js",
    "file"
  ],
  [
    "src/helpers/ethereum/getshop.js",
    "file/src/helpers/ethereum/getShop.js.html",
    "src/helpers/ethereum/getShop.js",
    "file"
  ],
  [
    "src/helpers/ethereum/gettransactionstatus.js",
    "file/src/helpers/ethereum/getTransactionStatus.js.html",
    "src/helpers/ethereum/getTransactionStatus.js",
    "file"
  ],
  [
    "src/helpers/ethereum/index.js",
    "file/src/helpers/ethereum/index.js.html",
    "src/helpers/ethereum/index.js",
    "file"
  ],
  [
    "src/helpers/ethereum/issmsreg.js",
    "file/src/helpers/ethereum/isSmsReg.js.html",
    "src/helpers/ethereum/isSmsReg.js",
    "file"
  ],
  [
    "src/helpers/ethereum/isweb3.js",
    "file/src/helpers/ethereum/isWeb3.js.html",
    "src/helpers/ethereum/isWeb3.js",
    "file"
  ],
  [
    "src/helpers/ethereum/iszoneshopopen.js",
    "file/src/helpers/ethereum/isZoneShopOpen.js.html",
    "src/helpers/ethereum/isZoneShopOpen.js",
    "file"
  ],
  [
    "src/helpers/ethereum/utils.js",
    "file/src/helpers/ethereum/utils.js.html",
    "src/helpers/ethereum/utils.js",
    "file"
  ],
  [
    "src/helpers/geocodeapi/geocodeapi.js",
    "file/src/helpers/geocodeAPI/geocodeAPI.js.html",
    "src/helpers/geocodeAPI/geocodeAPI.js",
    "file"
  ],
  [
    "src/helpers/geocodeapi/index.js",
    "file/src/helpers/geocodeAPI/index.js.html",
    "src/helpers/geocodeAPI/index.js",
    "file"
  ],
  [
    "src/helpers/get/get.js",
    "file/src/helpers/get/get.js.html",
    "src/helpers/get/get.js",
    "file"
  ],
  [
    "src/helpers/get/index.js",
    "file/src/helpers/get/index.js.html",
    "src/helpers/get/index.js",
    "file"
  ],
  [
    "src/helpers/index.js",
    "file/src/helpers/index.js.html",
    "src/helpers/index.js",
    "file"
  ],
  [
    "src/helpers/last/index.js",
    "file/src/helpers/last/index.js.html",
    "src/helpers/last/index.js",
    "file"
  ],
  [
    "src/helpers/last/last.js",
    "file/src/helpers/last/last.js.html",
    "src/helpers/last/last.js",
    "file"
  ],
  [
    "src/helpers/map/index.js",
    "file/src/helpers/map/index.js.html",
    "src/helpers/map/index.js",
    "file"
  ],
  [
    "src/helpers/parse/index.js",
    "file/src/helpers/parse/index.js.html",
    "src/helpers/parse/index.js",
    "file"
  ],
  [
    "src/helpers/parse/parse.js",
    "file/src/helpers/parse/parse.js.html",
    "src/helpers/parse/parse.js",
    "file"
  ],
  [
    "src/helpers/scrolltop/index.js",
    "file/src/helpers/scrollTop/index.js.html",
    "src/helpers/scrollTop/index.js",
    "file"
  ],
  [
    "src/helpers/scrolltop/scrolltop.js",
    "file/src/helpers/scrollTop/scrollTop.js.html",
    "src/helpers/scrollTop/scrollTop.js",
    "file"
  ],
  [
    "src/helpers/shake/index.js",
    "file/src/helpers/shake/index.js.html",
    "src/helpers/shake/index.js",
    "file"
  ],
  [
    "src/helpers/shake/shake.js",
    "file/src/helpers/shake/shake.js.html",
    "src/helpers/shake/shake.js",
    "file"
  ],
  [
    "src/helpers/stories/index.js",
    "file/src/helpers/stories/index.js.html",
    "src/helpers/stories/index.js",
    "file"
  ],
  [
    "src/helpers/timers/index.js",
    "file/src/helpers/timers/index.js.html",
    "src/helpers/timers/index.js",
    "file"
  ],
  [
    "src/helpers/timers/timers.js",
    "file/src/helpers/timers/timers.js.html",
    "src/helpers/timers/timers.js",
    "file"
  ],
  [
    "src/helpers/wait/index.js",
    "file/src/helpers/wait/index.js.html",
    "src/helpers/wait/index.js",
    "file"
  ],
  [
    "src/helpers/wait/wait.js",
    "file/src/helpers/wait/wait.js.html",
    "src/helpers/wait/wait.js",
    "file"
  ],
  [
    "src/middlewares/fetch/__mocks__/axios.js",
    "file/src/middlewares/fetch/__mocks__/axios.js.html",
    "src/middlewares/fetch/__mocks__/axios.js",
    "file"
  ],
  [
    "src/middlewares/fetch/index.js",
    "file/src/middlewares/fetch/index.js.html",
    "src/middlewares/fetch/index.js",
    "file"
  ],
  [
    "src/middlewares/index.js",
    "file/src/middlewares/index.js.html",
    "src/middlewares/index.js",
    "file"
  ],
  [
    "src/reducers/app/index.js",
    "file/src/reducers/app/index.js.html",
    "src/reducers/app/index.js",
    "file"
  ],
  [
    "src/reducers/index.js",
    "file/src/reducers/index.js.html",
    "src/reducers/index.js",
    "file"
  ],
  [
    "src/reducers/kyc/index.js",
    "file/src/reducers/kyc/index.js.html",
    "src/reducers/kyc/index.js",
    "file"
  ],
  [
    "src/reducers/map/index.js",
    "file/src/reducers/map/index.js.html",
    "src/reducers/map/index.js",
    "file"
  ],
  [
    "src/reducers/shop/index.js",
    "file/src/reducers/shop/index.js.html",
    "src/reducers/shop/index.js",
    "file"
  ],
  [
    "src/reducers/transaction/index.js",
    "file/src/reducers/transaction/index.js.html",
    "src/reducers/transaction/index.js",
    "file"
  ],
  [
    "src/reducers/user/index.js",
    "file/src/reducers/user/index.js.html",
    "src/reducers/user/index.js",
    "file"
  ],
  [
    "src/setuptests.js",
    "file/src/setupTests.js.html",
    "src/setupTests.js",
    "file"
  ],
  [
    "src/styles/globalstyles.js",
    "file/src/styles/globalStyles.js.html",
    "src/styles/globalStyles.js",
    "file"
  ],
  [
    "src/styles/medias.js",
    "file/src/styles/medias.js.html",
    "src/styles/medias.js",
    "file"
  ],
  [
    "src/styles/tokens.js",
    "file/src/styles/tokens.js.html",
    "src/styles/tokens.js",
    "file"
  ],
  [
    "src/translate/en/en.js",
    "file/src/translate/en/en.js.html",
    "src/translate/en/en.js",
    "file"
  ],
  [
    "src/translate/en/index.js",
    "file/src/translate/en/index.js.html",
    "src/translate/en/index.js",
    "file"
  ],
  [
    "src/translate/en/terms-en.js",
    "file/src/translate/en/terms-en.js.html",
    "src/translate/en/terms-en.js",
    "file"
  ]
]